version: '3.8'
services:
  sportsbet-automated-tests:
    image: playwright-automated-tests
    env_file:
      - .env
    build:
      context: .
      dockerfile: ./Dockerfile
    command: npm run test
    volumes:
      - ./playwright-report/:/app/playwright-report


